app:
  host: '0.0.0.0'
  port: 8000
  debug: true
  workers: 1

mongo:
  uri: 'mongodb://localhost:27017/'
  database: 'betbright'

redis:
  uri: 'redis://localhost'

rabbitmq:
  uri: 'amqp://guest:guest@127.0.0.1/'
